services:
  postgres:
    image: postgres:17
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    env_file:
      - .env
    # Named volume for db consistency
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: backend
    env_file:
      - .env
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend

volumes:
      postgres_data: